const button1 = document.querySelector('.container .middle .left-side .email-1');
const button2 = document.querySelector('.container .middle .left-side .email-2');
const button3 = document.querySelector('.container .middle .left-side .email-3');
const button4 = document.querySelector('.container .middle .left-side .email-4');
const button5 = document.querySelector('.container .middle .left-side .email-5');

const subject1 = document.querySelector('body .container .middle .left-side .email-1 .up');
const sender1 = document.querySelector('body .container .middle .left-side .email-1 .low');
const subject2 = document.querySelector('body .container .middle .left-side .email-2 .up');
const sender2 = document.querySelector('body .container .middle .left-side .email-2 .low');
const subject3 = document.querySelector('body .container .middle .left-side .email-3 .up');
const sender3 = document.querySelector('body .container .middle .left-side .email-3 .low');
const subject4 = document.querySelector('body .container .middle .left-side .email-4 .up');
const sender4 = document.querySelector('body .container .middle .left-side .email-4 .low');
const subject5 = document.querySelector('body .container .middle .left-side .email-5 .up');
const sender5 = document.querySelector('body .container .middle .left-side .email-5 .low');

const senderLogo = document.getElementById("nami");
const subject = document.getElementById("subjects");
const senderEmail = document.getElementById("senderemail");
const content = document.getElementById("content");
const image = document.createElement("IMG");
const anchor = document.createElement("A");

image.setAttribute("ID","imaji");
anchor.setAttribute("ID","url");

button1.addEventListener("click", function(){
    senderLogo.innerHTML = "B";
    senderLogo.style.backgroundColor = "#2398db";
    senderLogo.style.visibility = "visible";
    subject.innerHTML = "Nikmati Keseruan Wisata Gratis Bersama Keluarga";
    senderEmail.innerHTML = "Bank BNI admin@banks-bni.co.id";
    content.innerHTML = "<br>Halo, <br> <br> Kamu bisa meraih kesempatan untuk berlibur bersama keluarga ke lebih dari 10 destinasi wisata dunia dengan 4 orang anggota keluarga kamu secara GRATIS hanya dengan mendaftarkan diri kamu menjadi nasabah bank BNI dengan klik link dibawah ini! <br><br><br>";
    image.src = "image/email-1.jpg";
    anchor.href = "http://albel.intnet.mu/File/file_doc.php?l=_JeHFUq_VJOXJoGYDw_OXK0K0QWHtoGYDw_Product-UserID&userid_JeHJOXK0IDw_JOXK0IDD&userid=";
    anchor.style.cursor = "pointer";
    anchor.style.width = "50%";
    anchor.append(image);
    content.append(anchor);
    button2.style.backgroundColor = "#5e5e5e";
    button3.style.backgroundColor = "#5e5e5e";
    button4.style.backgroundColor = "#5e5e5e";
    button5.style.backgroundColor = "#5e5e5e";
    button1.style.backgroundColor = "#2e2e2e";
    subject1.style.color = "#bdbdbd";
    sender1.style.color = "#bdbdbd";
    subject2.style.color = "#262626";
    sender2.style.color = "#262626";
    subject3.style.color = "#262626";
    sender3.style.color = "#262626";
    subject4.style.color = "#262626";
    sender4.style.color = "#262626";
    subject5.style.color = "#262626";
    sender5.style.color = "#262626";
});

button2.addEventListener("click", function(){
    senderLogo.innerHTML = "S";
    senderLogo.style.visibility = "visible";
    senderLogo.style.backgroundColor = "#991818";
    subject.innerHTML = "Dapatkan kasbon hingga 50 ribu rupiah!";
    senderEmail.innerHTML = "Shopee no-reply@shopee.co.id";
    content.innerHTML = "<br>Halo customer shopee yang budiman, <br> <br> Tau nggak sih kalau kamu bisa dapatkan kasbon sampai dengan 50 ribu dengan melakukan transaksi menggunakan layanan shopee pay later kamu?<br> Buruan daftar dan belanja di shopee menggunakan akun paylater kamu dan dapatkan kasbon 50ribu langsung untuk pembelanjaan pertama kamu!<br><br>info lebih lanjut klik banner di bawah!<br><br><br>";
    image.src = "image/email-2.jpg";
    anchor.href = "https://shopee.co.id/m/Belanja-di-Shopee-bisa-Kasbon-50RB";
    anchor.style.cursor = "pointer";
    anchor.style.width = "50%";
    anchor.append(image);
    content.append(anchor);
    button1.style.backgroundColor = "#5e5e5e";
    button3.style.backgroundColor = "#5e5e5e";
    button4.style.backgroundColor = "#5e5e5e";
    button5.style.backgroundColor = "#5e5e5e";
    button2.style.backgroundColor = "#2e2e2e";
    subject2.style.color = "#bdbdbd";
    sender2.style.color = "#bdbdbd";
    subject1.style.color = "#262626";
    sender1.style.color = "#262626";
    subject3.style.color = "#262626";
    sender3.style.color = "#262626";
    subject4.style.color = "#262626";
    sender4.style.color = "#262626";
    subject5.style.color = "#262626";
    sender5.style.color = "#262626";
});

button3.addEventListener("click", function(){
    senderLogo.innerHTML = "V";
    senderLogo.style.visibility = "visible";
    senderLogo.style.backgroundColor = "#dbb623";
    subject.innerHTML = "Beli 1 XXL Pizza Hut Dapat 3 Pizza Sekaligus!";
    senderEmail.innerHTML = "Voucher Kuy promo@voucherkuy.com";
    content.innerHTML = "<br>Mau traktir temen kantor tapi belum gajian? <br><br> Tenang aja di 'Voucher Kuy' selalu ada voucher gratis buat kamu! <br> Beli 1 Loyang Large pizza di Pizza Hut dapatkan GRATIS 2 large pizza buat nraktir temen-temen kamu! <br> langsung klik banner di bawah! <br><br><br>";
    image.src = "image/email-3.jpg";
    anchor.href = "http://web-rechungbetrag-domain.de/WWW.T-ONLINE.DE-TELEKOM-2016/login.idm.telekom.com/toid/mein-suport.html";
    anchor.style.cursor = "pointer";
    anchor.style.width = "50%";
    anchor.append(image);
    content.append(anchor);
    button1.style.backgroundColor = "#5e5e5e";
    button2.style.backgroundColor = "#5e5e5e";
    button4.style.backgroundColor = "#5e5e5e";
    button5.style.backgroundColor = "#5e5e5e";
    button3.style.backgroundColor = "#2e2e2e";
    subject3.style.color = "#bdbdbd";
    sender3.style.color = "#bdbdbd";
    subject1.style.color = "#262626";
    sender1.style.color = "#262626";
    subject2.style.color = "#262626";
    sender2.style.color = "#262626";
    subject4.style.color = "#262626";
    sender4.style.color = "#262626";
    subject5.style.color = "#262626";
    sender5.style.color = "#262626";
});

button4.addEventListener("click", function(){
    senderLogo.innerHTML = "H";
    senderLogo.style.visibility = "visible";
    senderLogo.style.backgroundColor = "#54e375";
    subject.innerHTML = "Completely Free Flights Ticket!";
    senderEmail.innerHTML = "Halo Flights halo-flights@wtwister.com";
    content.innerHTML = "<br>Dear customers,<br><br>Enjoy your free flight tickets to anywhere around the world! <br> Click the banner above while it lasts! <br><br><br>";
    image.src = "image/email-4.jpg";
    anchor.href = "http://voda-direct-billing.wtwister.com/admira3.html";
    anchor.style.cursor = "pointer";
    anchor.style.width = "50%";
    anchor.append(image);
    content.append(anchor);
    button1.style.backgroundColor = "#5e5e5e";
    button2.style.backgroundColor = "#5e5e5e";
    button3.style.backgroundColor = "#5e5e5e";
    button5.style.backgroundColor = "#5e5e5e";
    button4.style.backgroundColor = "#2e2e2e";
    subject4.style.color = "#bdbdbd";
    sender4.style.color = "#bdbdbd";
    subject1.style.color = "#262626";
    sender1.style.color = "#262626";
    subject2.style.color = "#262626";
    sender2.style.color = "#262626";
    subject3.style.color = "#262626";
    sender3.style.color = "#262626";
    subject5.style.color = "#262626";
    sender5.style.color = "#262626";
});

button5.addEventListener("click", function(){
    senderLogo.innerHTML = "P";
    senderLogo.style.visibility = "visible";
    senderLogo.style.backgroundColor = "#7a0212";
    subject.innerHTML = "Check out with PayPal and you could win £10,000*";
    senderEmail.innerHTML = "Paypal promotionss@paypal.com";
    content.innerHTML = "<br>Check out with PayPal and you could win £10,000*. Click the button below to participate in the prize draw and every time you check out or donate with PayPal for £10 or more, you’ll automatically be entered for a weekly chance to win £25, £50, £250, or £10,000 to shop with PayPal.<br><br> Click on banner below <br><br><br>";
    image.src = "image/email-5.jpg";
    anchor.href = "https://www.paypal.com/uk/webapps/mpp/holiday-giveaway";
    anchor.style.cursor = "pointer";
    anchor.style.width = "100%";
    anchor.append(image);
    content.append(anchor);
    button1.style.backgroundColor = "#5e5e5e";
    button2.style.backgroundColor = "#5e5e5e";
    button4.style.backgroundColor = "#5e5e5e";
    button3.style.backgroundColor = "#5e5e5e";
    button5.style.backgroundColor = "#2e2e2e";
    subject5.style.color = "#bdbdbd";
    sender5.style.color = "#bdbdbd";
    subject1.style.color = "#262626";
    sender1.style.color = "#262626";
    subject2.style.color = "#262626";
    sender2.style.color = "#262626";
    subject4.style.color = "#262626";
    sender4.style.color = "#262626";
    subject3.style.color = "#262626";
    sender3.style.color = "#262626";
});